name: Bump Version
on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["*.js"]

jobs:
  bump-version:
    name: Bump Version on master
    runs-on: ubuntu-24.04
    concurrency: bump-version

    steps:
      - name: Checkout source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.ref }}

      - name: cat package.json
        run: cat ./package.json

      - name: Setup Node.JS
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: npm

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@71473b25295fe3907df2ff87cce295a0dce1b20b # v11.1.1
        with:
          tag-prefix: 'v'
        env:
          token: ${{secrets.TOKEN || secrets.GITHUB_TOKEN}}
          ref: ${{github.head_ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: cat package.json
        run: cat ./package.json

      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
